name: fastapi-template
services:
  app:
    depends_on:
      postgres_db:
        condition: service_healthy
      clickstack:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 3s
      timeout: 3s
      retries: 10

  postgres_db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_USERNAME: "user"
      POSTGRESQL_PASSWORD: "pass"
      POSTGRESQL_DATABASE: "my_db"
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d my_db" ]
      interval: 3s
      timeout: 3s
      retries: 10

  clickstack:
    image: docker.hyperdx.io/hyperdx/hyperdx-all-in-one:latest
    ports:
      - '8081:8080' # HyperDX UI
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP http receiver
