name: fastapi-template
services:
  app:
    depends_on:
      postgres_db:
        condition: service_healthy
      hyperdx:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql+psycopg://user:pass@postgres_db:5432/my_db"
      DB_ECHO_LOG: "1"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://hyperdx:4318"
      OTEL_SERVICE_NAME: "fastapi-template"
      HYPERDX_ENABLE_ADVANCED_NETWORK_CAPTURE: "1"
      HYPERDX_API_KEY: "put-your-api-key-here"  # CHANGE: get it from hyperdx and replace
    ports:
      - "8080:8080"
    restart: on-failure
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 3s
      timeout: 3s
      retries: 10

  postgres_db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_USERNAME: "user"
      POSTGRESQL_PASSWORD: "pass"
      POSTGRESQL_DATABASE: "my_db"
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d my_db" ]
      interval: 3s
      timeout: 3s
      retries: 10

  hyperdx:
    image: docker.hyperdx.io/hyperdx/hyperdx-all-in-one:latest
    ports:
      - '8081:8080' # HyperDX UI
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP http receiver
