name: fastapi-template
services:
  app:
    depends_on:
      postgres_db:
        condition: service_healthy
      clickstack:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: "production"
      DATABASE_URL: "postgresql+psycopg://user:pass@postgres_db:5432/my_db"
      HYPERDX_ENABLE_ADVANCED_NETWORK_CAPTURE: "1"
      OTEL_PYTHON_LOG_CORRELATION: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://clickstack:4318"
      OTEL_SERVICE_NAME: "fastapi-template"
      HYPERDX_API_KEY: "${HYPERDX_API_KEY:-}"
    ports:
      - "8080:8080"
    restart: no
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 3s
      timeout: 3s
      retries: 10

  postgres_db:
    image: postgres:17
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "my_db"
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d my_db" ]
      interval: 3s
      timeout: 3s
      retries: 10

  clickstack:
    image: clickhouse/clickstack-local:latest
    ports:
      - '8081:8080' # HyperDX UI
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP http receiver

volumes:
  postgres_data:
