version: "3"

services:
    postgres_db:
        image: bitnami/postgresql:latest
        environment:
            - POSTGRESQL_USERNAME=user
            - POSTGRESQL_PASSWORD=pass
            - POSTGRESQL_DATABASE=my_db
        ports:
            - "5434:5432"
